kotlin.code.style=official
# Increase the maximum memory of Kotlin daemon process (recommended 4-6GB)
kotlin.daemon.jvmargs=-Xmx6g
#Gradle
org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# `android.version.code` Also used in ios
# major(1)-minor(pad to 2)-patch(1)-meta(1)
android.namespace=com.ciyin.app
android.applicationid=com.ciyin.nomikit
android.compile.sdk=36
android.min.sdk=26
android.version.code=100000
android.version.name=1.0.0
# JBR must have JCEF bundled
jvm.toolchain.vendor=jetbrains
jvm.toolchain.version=17
# multiplatform-lib-targets.gradle.kts
multiplatform.enable.desktop=true
multiplatform.enable.ios=true
multiplatform.enable.web=false
#multiplatform.enable.js=true
#multiplatform.enable.wasmJs=true
